# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./data/ludii/sft
dataset_config: all
dataset_num_proc: 12

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: "no"
eval_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: ""
hub_strategy: every_save
learning_rate: 1e-04
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: false
max_seq_length: 768
max_steps: -1
num_train_epochs: 3
output_dir: log/models/sft/Qwen2.5-1.5B-Instruct_SFT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 1000
seed: 42
warmup_ratio: 0.03
