# Model arguments
model_name_or_path: ./log/models/sft/Qwen2.5-1.5B-Instruct_SFT
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./data/ludii/grpo
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Instruct_SFT_GRPO
hub_strategy: every_save
learning_rate: 3.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
max_completion_length: 512
max_steps: -1
num_train_epochs: 1
output_dir: log/models//grpo/Qwen2.5-1.5B-Instruct_SFT_GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
seed: 42
warmup_ratio: 0.1
num_generations: 4
temperature: 0.9
beta: 0.04
